# ----- top-level run controls -----
jobs    = 16               # number of workers
out_dir = "out/"           # output root (will be normalized with a trailing /)

# ----- SMA settings -----
[sma]
# Choose either single or range (but not both). If both are present, the CLI picks mode later.
# Single mode:
# short = 35
# long  = 98

# Range mode:
short_range = [25, 40, 1]   # min, max, step
long_range  = [90, 110, 1] # min, max, step

# ----- inputs -----
[inputs]
files = [
    "wse_stocks/slv.txt"
]
