# ----- top-level run controls -----
jobs    = 16               # number of workers
out_dir = "out/"           # output root (will be normalized with a trailing /)

# ----- SMA settings -----
[sma]
# Choose either single or range (but not both). If both are present, the CLI picks mode later.
# Single mode:
# short = 35
# long  = 98

# Range mode:
short_range = [5, 60, 1]   # min, max, step
long_range  = [80, 220, 1] # min, max, step'

# ----- inputs -----
[inputs]
files = [
    "wse_stocks/1at.txt",
    "wse_stocks/acg.txt",
    "wse_stocks/ago.txt",
    "wse_stocks/all.txt",
    "wse_stocks/amb.txt",
    "wse_stocks/amc.txt",
    "wse_stocks/apt.txt",
    "wse_stocks/arh.txt",
    "wse_stocks/atc.txt",
    "wse_stocks/abs.txt",
    "wse_stocks/ast.txt",
    "wse_stocks/bcx.txt",
    "wse_stocks/bio.txt",
    "wse_stocks/blo.txt",
    "wse_stocks/lwb.txt",
    "wse_stocks/brs.txt",
    "wse_stocks/bos.txt",
    "wse_stocks/bmc.txt",
    "wse_stocks/ctx.txt",
    "wse_stocks/cig.txt",
    "wse_stocks/cog.txt",
    "wse_stocks/clc.txt",
    "wse_stocks/cmp.txt",
    "wse_stocks/crj.txt",
    "wse_stocks/cri.txt",
    "wse_stocks/dat.txt",
    "wse_stocks/dcr.txt",
    "wse_stocks/dia.txt",
    "wse_stocks/ech.txt",
    "wse_stocks/elt.txt",
    "wse_stocks/ent.txt",
    "wse_stocks/erb.txt",
    "wse_stocks/fro.txt",
    "wse_stocks/fte.txt",
    "wse_stocks/grx.txt",
    "wse_stocks/gea.txt",
    "wse_stocks/kgn.txt",
    "wse_stocks/mab.txt",
    "wse_stocks/mci.txt",
    "wse_stocks/mdg.txt",
    "wse_stocks/mnc.txt",
    "wse_stocks/mrc.txt",
    "wse_stocks/mcr.txt",
    "wse_stocks/mlg.txt",
    "wse_stocks/mls.txt",
    "wse_stocks/moc.txt",
    "wse_stocks/msz.txt",
    "wse_stocks/mur.txt",
    "wse_stocks/ond.txt",
    "wse_stocks/opn.txt",
    "wse_stocks/pcr.txt",
    "wse_stocks/pbx.txt",
    "wse_stocks/plw.txt",
    "wse_stocks/pxm.txt",
    "wse_stocks/qrs.txt",
    "wse_stocks/rnk.txt",
    "wse_stocks/rvu.txt",
    "wse_stocks/snk.txt",
    "wse_stocks/scp.txt",
    "wse_stocks/sel.txt",
    "wse_stocks/slv.txt",
    "wse_stocks/sho.txt",
    "wse_stocks/ska.txt",
    "wse_stocks/sve.txt",
    "wse_stocks/stx.txt",
    "wse_stocks/stp.txt",
    "wse_stocks/sgn.txt",
    "wse_stocks/tar.txt",
    "wse_stocks/tor.txt",
    "wse_stocks/toa.txt",
    "wse_stocks/uni.txt",
    "wse_stocks/unt.txt",
    "wse_stocks/vgo.txt",
    "wse_stocks/vot.txt",
    "wse_stocks/vrg.txt",
    "wse_stocks/wwl.txt",
    "wse_stocks/wlt.txt",
    "wse_stocks/wtn.txt",
    "wse_stocks/xtp.txt",
    "wse_stocks/zep.txt"
]